FROM golang:1.25 AS build

WORKDIR /src

COPY go.mod go.sum ./
RUN go mod download

COPY telegramBot /src/telegramBot

ENV CGO_ENABLED=0
RUN cd /src && go build -o /telegram-bot telegramBot/main.go

FROM alpine:3.20

RUN adduser -D app
USER app

COPY --from=build /telegram-bot /telegram-bot

ENTRYPOINT ["/telegram-bot"]
